### ISSUE TITLE
cURL not listed as dependency in componser.json

### ISSUE THREAD

**Issue by Dwarfex** [jamesiarmes/php-ntlm#7]
See title: cURL PHP Extension not listed as dependency in componser.json

**Comment by cr998** [comment]
You must to take a look in this [http://php.net/manual/es/curl.installation.php](http://php.net/manual/es/curl.installation.php), cURL is not a depencency, cURL is an php extension that you must to install on your server

**Comment by Dwarfex** [comment]
@cr998 
Of course requirements to the environment can / should also be listed in the composer file:

In the current composer.json is php and the soap extension also listed.

`
"require": {
    "php": ">=5.3.9",
    "ext-soap": "*"
  },`

one could easily add 

`"ext-curl": "^7.2"` 

to the composer.json. Also curl extension is required in a Version greater than 7.2
